#!/usr/bin/env bash
# Mechanical guardrails for writer-agent PRs (branches agent/*).
# Config: .github/agent-guard.conf (AG_PROTECTED, AG_TESTS_GLOB, AG_TEST_MARKERS,
#         AG_MAX_FILES, AG_MAX_LINES) — generated by kod-hatti onboarding.
# Usage: agent-guard.sh <base-sha> <head-sha>
set -euo pipefail

BASE="$1"
HEAD="$2"
# shellcheck disable=SC1091
source "$(dirname "$0")/../agent-guard.conf"
MAX_FILES="${AG_MAX_FILES:-3}"
MAX_LINES="${AG_MAX_LINES:-299}"
fail=0

err() { echo "::error::$*"; fail=1; }

files=$(git diff --name-only "$BASE" "$HEAD")
file_count=$(printf '%s\n' "$files" | grep -c . || true)
[ "$file_count" -gt "$MAX_FILES" ] && err "changed files: $file_count (max $MAX_FILES)"

lines=$(git diff --numstat "$BASE" "$HEAD" | awk '{a+=$1; d+=$2} END {print a+d+0}')
[ "$lines" -gt "$MAX_LINES" ] && err "changed lines: $lines (max $MAX_LINES)"

while IFS= read -r f; do
  [ -z "$f" ] && continue
  printf '%s\n' "$f" | grep -Eq "$AG_PROTECTED" && err "forbidden path touched: $f"
done <<< "$files"

# Test files are add-only: no removed/changed lines carrying a test marker.
test_files=$(printf '%s\n' "$files" | grep -E "$AG_TESTS_GLOB" || true)
if [ -n "$test_files" ]; then
  removed=$(printf '%s\n' "$test_files" | xargs -I{} git diff -U0 "$BASE" "$HEAD" -- {} \
    | grep -E '^-[^-]' | grep -E "$AG_TEST_MARKERS" || true)
  if [ -n "$removed" ]; then
    err "existing test or assertion lines removed or changed:"
    printf '%s\n' "$removed"
  fi
fi

count_tests() {
  git ls-tree -r --name-only "$1" | grep -E "$AG_TESTS_GLOB" \
    | while IFS= read -r f; do git show "$1:$f" 2>/dev/null; done \
    | grep -Ec "$AG_TEST_MARKERS" || true
}
base_tests=$(count_tests "$BASE")
head_tests=$(count_tests "$HEAD")
[ "$head_tests" -lt "$base_tests" ] && err "test/assert count dropped: $base_tests -> $head_tests"

echo "files=$file_count lines=$lines tests=$base_tests->$head_tests"
exit "$fail"
